"../data/input/frames/cars4/cars4-001.ppm";
"../data/input/frames/cars4/cars4-002.ppm";
"../data/input/frames/cars4/cars4-003.ppm";
"../data/input/frames/cars4/cars4-004.ppm";
"../data/input/frames/cars4/cars4-005.ppm";
"../data/input/frames/cars4/cars4-006.ppm";
"../data/input/frames/cars4/cars4-007.ppm";
"../data/input/frames/cars4/cars4-008.ppm";
"../data/input/frames/cars4/cars4-009.ppm";
"../data/input/frames/cars4/cars4-010.ppm";
"../data/input/frames/cars4/cars4-011.ppm";
"../data/input/frames/cars4/cars4-012.ppm";
"../data/input/frames/cars4/cars4-013.ppm";
"../data/input/frames/cars4/cars4-014.ppm";
"../data/input/frames/cars4/cars4-015.ppm";
"../data/input/frames/cars4/cars4-016.ppm";
"../data/input/frames/cars4/cars4-017.ppm";
"../data/input/frames/cars4/cars4-018.ppm";
"../data/input/frames/cars4/cars4-019.ppm";
"../data/input/frames/cars4/cars4-020.ppm";
"../data/input/frames/cars4/cars4-021.ppm";
"../data/input/frames/cars4/cars4-022.ppm";
"../data/input/frames/cars4/cars4-023.ppm";
"../data/input/frames/cars4/cars4-024.ppm";
"../data/input/frames/cars4/cars4-025.ppm";
"../data/input/frames/cars4/cars4-026.ppm";
"../data/input/frames/cars4/cars4-027.ppm";
"../data/input/frames/cars4/cars4-028.ppm";
"../data/input/frames/cars4/cars4-029.ppm";
"../data/input/frames/cars4/cars4-030.ppm";
"../data/input/frames/cars4/cars4-031.ppm";
"../data/input/frames/cars4/cars4-032.ppm";
"../data/input/frames/cars4/cars4-033.ppm";
"../data/input/frames/cars4/cars4-034.ppm";
"../data/input/frames/cars4/cars4-035.ppm";
"../data/input/frames/cars4/cars4-036.ppm";
"../data/input/frames/cars4/cars4-037.ppm";
"../data/input/frames/cars4/cars4-038.ppm";
"../data/input/frames/cars4/cars4-039.ppm";
"../data/input/frames/cars4/cars4-040.ppm";
"../data/input/frames/cars4/cars4-041.ppm";
"../data/input/frames/cars4/cars4-042.ppm";
"../data/input/frames/cars4/cars4-043.ppm";
"../data/input/frames/cars4/cars4-044.ppm";
"../data/input/frames/cars4/cars4-045.ppm";
"../data/input/frames/cars4/cars4-046.ppm";
"../data/input/frames/cars4/cars4-047.ppm";
"../data/input/frames/cars4/cars4-048.ppm";
"../data/input/frames/cars4/cars4-049.ppm";
"../data/input/frames/cars4/cars4-050.ppm";
"../data/input/frames/cars4/cars4-051.ppm";
"../data/input/frames/cars4/cars4-052.ppm";
"../data/input/frames/cars4/cars4-053.ppm";
"../data/input/frames/cars4/cars4-054.ppm";