"../data/inter/frames/cars4/4/cars4-001.png";
"../data/inter/frames/cars4/4/cars4-002.png";
"../data/inter/frames/cars4/4/cars4-003.png";
"../data/inter/frames/cars4/4/cars4-004.png";
"../data/inter/frames/cars4/4/cars4-005.png";
"../data/inter/frames/cars4/4/cars4-006.png";
"../data/inter/frames/cars4/4/cars4-007.png";
"../data/inter/frames/cars4/4/cars4-008.png";
"../data/inter/frames/cars4/4/cars4-009.png";
"../data/inter/frames/cars4/4/cars4-010.png";
"../data/inter/frames/cars4/4/cars4-011.png";
"../data/inter/frames/cars4/4/cars4-012.png";
"../data/inter/frames/cars4/4/cars4-013.png";
"../data/inter/frames/cars4/4/cars4-014.png";
"../data/inter/frames/cars4/4/cars4-015.png";
"../data/inter/frames/cars4/4/cars4-016.png";
"../data/inter/frames/cars4/4/cars4-017.png";
"../data/inter/frames/cars4/4/cars4-018.png";
"../data/inter/frames/cars4/4/cars4-019.png";
"../data/inter/frames/cars4/4/cars4-020.png";
"../data/inter/frames/cars4/4/cars4-021.png";
"../data/inter/frames/cars4/4/cars4-022.png";
"../data/inter/frames/cars4/4/cars4-023.png";
"../data/inter/frames/cars4/4/cars4-024.png";
"../data/inter/frames/cars4/4/cars4-025.png";
"../data/inter/frames/cars4/4/cars4-026.png";
"../data/inter/frames/cars4/4/cars4-027.png";
"../data/inter/frames/cars4/4/cars4-028.png";
"../data/inter/frames/cars4/4/cars4-029.png";
"../data/inter/frames/cars4/4/cars4-030.png";
"../data/inter/frames/cars4/4/cars4-031.png";
"../data/inter/frames/cars4/4/cars4-032.png";
"../data/inter/frames/cars4/4/cars4-033.png";
"../data/inter/frames/cars4/4/cars4-034.png";
"../data/inter/frames/cars4/4/cars4-035.png";
"../data/inter/frames/cars4/4/cars4-036.png";
"../data/inter/frames/cars4/4/cars4-037.png";
"../data/inter/frames/cars4/4/cars4-038.png";
"../data/inter/frames/cars4/4/cars4-039.png";
"../data/inter/frames/cars4/4/cars4-040.png";
"../data/inter/frames/cars4/4/cars4-042.png";
"../data/inter/frames/cars4/4/cars4-043.png";
"../data/inter/frames/cars4/4/cars4-044.png";
"../data/inter/frames/cars4/4/cars4-045.png";
"../data/inter/frames/cars4/4/cars4-046.png";
