"../data/inter/frames/cars4/1/cars4-044.png";
"../data/inter/frames/cars4/1/cars4-045.png";
"../data/inter/frames/cars4/1/cars4-046.png";
"../data/inter/frames/cars4/1/cars4-047.png";
"../data/inter/frames/cars4/1/cars4-048.png";
"../data/inter/frames/cars4/1/cars4-049.png";
"../data/inter/frames/cars4/1/cars4-050.png";
"../data/inter/frames/cars4/1/cars4-051.png";
"../data/inter/frames/cars4/1/cars4-052.png";
