"../data/input/frames/cars5/cars5-001.ppm";
"../data/input/frames/cars5/cars5-002.ppm";
"../data/input/frames/cars5/cars5-003.ppm";
"../data/input/frames/cars5/cars5-004.ppm";
"../data/input/frames/cars5/cars5-005.ppm";
"../data/input/frames/cars5/cars5-006.ppm";
"../data/input/frames/cars5/cars5-007.ppm";
"../data/input/frames/cars5/cars5-008.ppm";
"../data/input/frames/cars5/cars5-009.ppm";
"../data/input/frames/cars5/cars5-010.ppm";
"../data/input/frames/cars5/cars5-011.ppm";
"../data/input/frames/cars5/cars5-012.ppm";
"../data/input/frames/cars5/cars5-013.ppm";
"../data/input/frames/cars5/cars5-014.ppm";
"../data/input/frames/cars5/cars5-015.ppm";
"../data/input/frames/cars5/cars5-016.ppm";
"../data/input/frames/cars5/cars5-017.ppm";
"../data/input/frames/cars5/cars5-018.ppm";
"../data/input/frames/cars5/cars5-019.ppm";
"../data/input/frames/cars5/cars5-020.ppm";
"../data/input/frames/cars5/cars5-021.ppm";
"../data/input/frames/cars5/cars5-022.ppm";
"../data/input/frames/cars5/cars5-023.ppm";
"../data/input/frames/cars5/cars5-024.ppm";
"../data/input/frames/cars5/cars5-025.ppm";
"../data/input/frames/cars5/cars5-026.ppm";
"../data/input/frames/cars5/cars5-027.ppm";
"../data/input/frames/cars5/cars5-028.ppm";
"../data/input/frames/cars5/cars5-029.ppm";
"../data/input/frames/cars5/cars5-030.ppm";
"../data/input/frames/cars5/cars5-031.ppm";
"../data/input/frames/cars5/cars5-032.ppm";
"../data/input/frames/cars5/cars5-033.ppm";
"../data/input/frames/cars5/cars5-034.ppm";
"../data/input/frames/cars5/cars5-035.ppm";
"../data/input/frames/cars5/cars5-036.ppm";
"../data/input/frames/cars5/cars5-037.ppm";
